Params.T1=0;
Params.T2=0.15;
Params.Fss=24414.0625;
Params.SPL=80;
Params.MdB=30;
Params.ModType='dB';
Params.Sound='MR';
Params.NBlocks=400;
Params.UF=10;
Params.sprtype='float';
Params.p=0.001;
Params.SModType='dB';
spikeClusters = '/Users/shannon1/Documents/F19/neuroResearch/nSTRF/spike_times_ripple_clust_new.mat';
sprfile = '/Users/shannon1/Documents/F19/neuroResearch/nSTRF/DNR_Cortex_96k5min_4_50.spr';
Trig = '/Users/shannon1/Documents/F19/neuroResearch/nSTRF/AudiResp_16_24-190326-154559_triggers.mat';
version = 'st_clu';
analyzeAll = 'n';
numClusters = 4;
getIndividual(Params, spikeClusters, sprfile, Trig, version, analyzeAll, numClusters);
getPaired(Params, spikeClusters, sprfile, Trig, version, analyzeAll, numClusters);